# Cloudflare Pages Configuration for Skiphire Showcase
name = "skiphire-showcase"
compatibility_date = "2025-05-12"

[build]
command = "pnpm build"
output_directory = "dist"
node_compatibility_date = "2023-10-30" # Using a stable Node version

[build.environment]
NODE_VERSION = "18"

[site]
bucket = "./dist"

# Configure Single Page Application (SPA) settings
[site.spa]
enabled = true

# Asset optimization settings
[optimization]
compress = true

# Set up redirects and rewrites for client-side routing
[[routes]]
pattern = "/*"
script = ""
rewrite = "/index.html"

# Environment variable configuration
[env.production]
# Add production-specific environment variables here
# MY_VARIABLE = "value"

[env.preview]
# Add preview-specific environment variables here
# MY_VARIABLE = "value"
